version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 7777:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/extension:/usr/share/postgresql/15/extension
      - ./postgres/init:/docker-entrypoint-initdb.d
    # command: ["postgres", "-c", "shared_preload_libraries=pg_pathman"]
